// <auto-generated />
using System;
using MVC_ComponentesCodeFirst.App_Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_ComponentesCodeFirst.Migrations
{
    [DbContext(typeof(ComponentesCodeFirstContext))]
    [Migration("20230821091246_MigracionOneToMany")]
    partial class MigracionOneToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_ComponentesCodeFirst.Models.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<int?>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Grados")
                        .HasColumnType("int");

                    b.Property<long?>("Megas")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroDeSerie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("OrdenadorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenadorId");

                    b.ToTable("Componentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = 0,
                            Cores = 9,
                            Descripcion = "Procesador Intel i7",
                            Grados = 10,
                            Megas = 0L,
                            NumeroDeSerie = "789-XCS",
                            Precio = 134m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = 0,
                            Cores = 10,
                            Descripcion = "Procesador Intel i7",
                            Grados = 12,
                            Megas = 0L,
                            NumeroDeSerie = "789-XCD",
                            Precio = 138m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = 0,
                            Cores = 11,
                            Descripcion = "Procesador Intel i7",
                            Grados = 12,
                            Megas = 0L,
                            NumeroDeSerie = "789-XCT",
                            Precio = 138m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = 1,
                            Cores = 0,
                            Descripcion = "Banco De Memoria SDRAM",
                            Grados = 10,
                            Megas = 512L,
                            NumeroDeSerie = "879FH",
                            Precio = 100m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = 1,
                            Cores = 0,
                            Descripcion = "Banco De Memoria SDRAM",
                            Grados = 15,
                            Megas = 1024L,
                            NumeroDeSerie = "879FH-L",
                            Precio = 125m
                        },
                        new
                        {
                            Id = 6,
                            Categoria = 1,
                            Cores = 0,
                            Descripcion = "Banco De Memoria SDRAM",
                            Grados = 24,
                            Megas = 2048L,
                            NumeroDeSerie = "879FH-T",
                            Precio = 150m
                        },
                        new
                        {
                            Id = 7,
                            Categoria = 2,
                            Cores = 0,
                            Descripcion = "DiscoDuro SanDisk",
                            Grados = 10,
                            Megas = 512000L,
                            NumeroDeSerie = "789-XX",
                            Precio = 50m
                        },
                        new
                        {
                            Id = 8,
                            Categoria = 2,
                            Cores = 0,
                            Descripcion = "DiscoDuro SanDisk",
                            Grados = 29,
                            Megas = 1024000L,
                            NumeroDeSerie = "789-XX-2",
                            Precio = 90m
                        },
                        new
                        {
                            Id = 9,
                            Categoria = 2,
                            Cores = 0,
                            Descripcion = "DiscoDuro SanDisk",
                            Grados = 39,
                            Megas = 2048000L,
                            NumeroDeSerie = "789-XX-3",
                            Precio = 128m
                        },
                        new
                        {
                            Id = 10,
                            Categoria = 0,
                            Cores = 10,
                            Descripcion = "Procesador Ryzen AMD",
                            Grados = 30,
                            Megas = 0L,
                            NumeroDeSerie = "797-X",
                            Precio = 78m
                        },
                        new
                        {
                            Id = 11,
                            Categoria = 0,
                            Cores = 29,
                            Descripcion = "Procesador Ryzen AMD",
                            Grados = 30,
                            Megas = 0L,
                            NumeroDeSerie = "797-X2",
                            Precio = 178m
                        },
                        new
                        {
                            Id = 12,
                            Categoria = 0,
                            Cores = 34,
                            Descripcion = "Procesador Ryzen AMD",
                            Grados = 60,
                            Megas = 0L,
                            NumeroDeSerie = "797-X3",
                            Precio = 278m
                        },
                        new
                        {
                            Id = 13,
                            Categoria = 2,
                            Cores = 0,
                            Descripcion = "Disco Mecánico Patatin",
                            Grados = 35,
                            Megas = 250L,
                            NumeroDeSerie = "788-fg",
                            Precio = 37m
                        },
                        new
                        {
                            Id = 14,
                            Categoria = 2,
                            Cores = 0,
                            Descripcion = "Disco Mecánico Patatin",
                            Grados = 35,
                            Megas = 250L,
                            NumeroDeSerie = "788-fg-2",
                            Precio = 67m
                        },
                        new
                        {
                            Id = 15,
                            Categoria = 2,
                            Cores = 0,
                            Descripcion = "Disco Mecánico Patatin",
                            Grados = 35,
                            Megas = 250L,
                            NumeroDeSerie = "788-fg-3",
                            Precio = 97m
                        });
                });

            modelBuilder.Entity("MVC_ComponentesCodeFirst.Models.Ordenador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Propietario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ordenadores");
                });

            modelBuilder.Entity("MVC_ComponentesCodeFirst.Models.Componente", b =>
                {
                    b.HasOne("MVC_ComponentesCodeFirst.Models.Ordenador", null)
                        .WithMany("Componentes")
                        .HasForeignKey("OrdenadorId");
                });

            modelBuilder.Entity("MVC_ComponentesCodeFirst.Models.Ordenador", b =>
                {
                    b.Navigation("Componentes");
                });
#pragma warning restore 612, 618
        }
    }
}
